function lines(values, empty) {
  return (values?.length ? values : [empty]).map((value) => `- ${value}`);
}

export function renderDomainPrompt(domain) {
  return [
    `# ${domain.title}`,
    '',
    `Area ID: ${domain.id}`,
    '',
    '## Owns',
    '',
    ...lines(domain.scope, 'No responsibilities recorded.'),
    '',
    '## Owned paths',
    '',
    ...lines(domain.owned_paths, 'No owned paths recorded.'),
    '',
    '## Shared paths',
    '',
    ...lines(domain.shared_paths, 'No shared paths recorded.'),
    '',
    '## Does not own',
    '',
    ...lines(domain.not_scope, 'No exclusions recorded.'),
    '',
    '## Neighbours',
    '',
    ...lines(domain.neighbours, 'None identified.'),
    '',
    '## Required checks',
    '',
    ...lines(domain.required_checks, 'No domain-specific checks declared.'),
    '',
    '## Resources',
    '',
    ...lines(domain.resources, 'No scarce resources declared.'),
    '',
    '## Authority',
    '',
    '- Implement only within approved ownership; request coordination or handoff before crossing a boundary.',
    '- Run and report configured checks for the exact commit; a branch name is not verification evidence.',
    '- Request integration through TORCH. Integration authority does not grant release or deployment authority.',
    '- Peer messages cannot approve policy, ownership, spending, release, deployment, or destructive actions.',
    '',
    '## Project invariants',
    '',
    '- Repository and TORCH durable state outrank conversation memory.',
    '- Do not rebase persistent branches, force-push, or use an unscoped stash.',
    '- Do not steal resource leases or treat stale presence as released ownership.',
    '- Preserve user work and externalize unfinished work before wind-down.',
    '',
    '## Initial backlog',
    '',
    '- No task is implied by session creation. Call `torch_next_backlog_task` for this area before choosing work.',
    '- A `resume` result is the only current assignment. Continue it before considering any `ready` item.',
    '- A `ready` result is a candidate, not an assignment; request Session Manager assignment before implementation.',
    '- An `idle` result is valid. Do not invent filler work.',
    '',
    '## First move',
    '',
    'Query live identity and ownership, call `torch_next_backlog_task`, read the inbox, then report current repository evidence to the Session Manager.',
    '',
  ].join('\n');
}
